version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    ports:
      - '4406:3306'
    environment:
      MYSQL_USER: 'test1'
      MYSQL_PASSWORD: 'test1'
      MYSQL_ROOT_PASSWORD: 'password'


  php:
    build: ./docker/php
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8080:8080
#    command: php -S 0.0.0.0:8000 -t /app
    command: php crypto_exchange/artisan serve --host=0.0.0.0 --port=8080